language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
env:
  - CI=true
jobs:
  include:
    - stage: "Tests"
      name: "ES Lint"
      script: npm run lint:js
    - name: "CSS Lint"
      script: npm run lint:css
    - name: "Unit Test Execution"
      script: npm run test
    - stage: deployment
      name: "Deploy artifacts to Netlify"
      before_deploy:
        - npm run build
        - npm install netlify-cli -g
      deploy:
        provider: script
        script: netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN -p --dir ./build
        skip_cleanup: true
        on:
          branch: master
